QUALITY_BEST_GROUP_ID = 1
QUALITY_WORST_GROUP_ID = 2
QUALITY_AT_MOST_GROUP_ID = 3
QUALITY_AT_LEAST_GROUP_ID = 4

STREAM_BOTH_GROUP_ID = 1
STREAM_AUDIO_GROUP_ID = 2

SUBTITLE_ALL_GROUP_ID = 1
SUBTITLE_RULES_GROUP_ID = 2

SPONSORBLOCK_DISABLE_GROUP_ID = 1
SPONSORBLOCK_REMOVE_GROUP_ID = 2
SPONSORBLOCK_MARK_GROUP_ID = 3

SPONSORBLOCK_SECTION_DEFAULT_GROUP_ID = 1
SPONSORBLOCK_SECTION_ALL_GROUP_ID = 2
SPONSORBLOCK_SECTION_CHAPTER_GROUP_ID = 3
SPONSORBLOCK_SECTION_SPONSOR_GROUP_ID = 4
SPONSORBLOCK_SECTION_INTRO_GROUP_ID = 5
SPONSORBLOCK_SECTION_OUTRO_GROUP_ID = 6
SPONSORBLOCK_SECTION_SELFPROMO_GROUP_ID = 7
SPONSORBLOCK_SECTION_PREVIEW_GROUP_ID = 8
SPONSORBLOCK_SECTION_FILLER_GROUP_ID = 9
SPONSORBLOCK_SECTION_INTERACTION_GROUP_ID = 10
SPONSORBLOCK_SECTION_MUSIC_OFFTOPIC_GROUP_ID = 11
SPONSORBLOCK_SECTION_POI_HIGHLIGHT_GROUP_ID = 12

PYML_EXPORT_GROUP_ID = 1
PYML_TAG_GROUP_ID = 2
PYML_EXTEND_GROUP_ID = 3
PYML_SPLIT_GROUP_ID = 4

AFK_NOTHING_GROUP_ID = 1
AFK_SHUTDOWN_GROUP_ID = 2
AFK_RESTART_GROUP_ID = 3
AFK_CLOSE_GROUP_ID = 4
AFK_COMMAND_GROUP_ID = 5
